### PR TITLE
Fix exception in diff code with arrays

### LINKED ISSUE #178: bug: equal comparing null vs. array
The following assert is causing `uvu` throws:

```
assert.equal(null, [1]);
```

it's causing an error:

```
Cannot read properties of null (reading 'slice')
```

which is coming from `diff`:

Screenshot 2021-12-16 at 00 59 49

also, `assert.equal({}, [1]);` is failing too.

### PR DESCRIPTION
**Pull request by marvinhagemeister**
This PR addresses an issue where asserting arrays with non-arrays would crash the diff code instead of throwing an assertion error.

Fixes #178

### CODE REVIEW

File: test/assert.js [hunk 1]
```diff
@@ -198,6 +198,16 @@ equal('should use deep equality checks', () => {
...
 
+// Issue #178
+equal('should throw assertion error on array type mismatch', () => {
+	try {
+		$.equal(null, [1]);
+		assert.unreachable();
+	} catch (err) {
+		assert.instance(err, $.Assertion);
+	}
+})
```
Comment (lukeed) [inline test/assert.js:209]:
```suggestion
equal('should throw assertion error on array type mismatch', () => {
	try {
		$.equal(null, []);
		assert.unreachable();
	} catch (err) {
		assert.instance(err, $.Assertion);
	}

	try {
		$.equal([], null);
		assert.unreachable();
	} catch (err) {
		assert.instance(err, $.Assertion);
	}

});
```

File: src/diff.js [hunk 2]
```diff
@@ -192,7 +192,9 @@ export function stringify(input) {
 }
 
 export function compare(input, expect) {
-	if (Array.isArray(expect)) return arrays(input, expect);
+	if (Array.isArray(expect) && Array.isArray(input)) {
+		return arrays(input, expect);
+	}
```
Comment (lukeed) [inline src/diff.js:197]:
```suggestion
	if (Array.isArray(expect) && Array.isArray(input)) return arrays(input, expect);
```

**Comment by lukeed** [comment]
Thank you sir~!
